### ISSUE TITLE
destroy fleximages

### ISSUE THREAD

**Issue by berndschimmer** [Pixabay/jQuery-flexImages#13]
Hi,

how do i destroy flexImages? 
I need this for dynamic activate and deactivate flexImages on an image list.

thx for your time!
Bernd

**Comment by SimonSteinberger** [comment]
Unfortunately, a feature that doesn't exist, yet. I'm kept very busy these days, but I hope I'll soon be able to find the time for this implementation. Or I can merge a pull request when available.

**Comment by SimonSteinberger** [comment]
First off, thanks for your pull request and the contributions to the plugin:
https://github.com/Pixabay/jQuery-flexImages/pull/14

I've given this a lot of thought - over and over again. The thing is: I'm trying to keep this plugin as simple and efficient as possible. And so far, I assume the destroy method will hardly ever be used - at least not by the majority. Usually, when creating an image grid of that kind, you'll want to keep it or update it. And you can update it without having to destroy it first. I do believe, there are circumstances where a destroy method may be important, but since it's not a regular thing, I'd prefer not to include it by default in the code repo.

If others join in and vote for including the destroy method, we'll very likely do so :-)

Cheers, Simon

**Comment by OriginalEXE** [comment]
+1 for the destroy method. I am using the grid in a client-rendered web app and destroy method would come in very handy. Right now I have to get around it by fetching data-t and removing the event listener myself.

**Comment by Julien76** [comment]
+1 for the destroy gallery. I'm trying to use flexImages together with smoothState scripts, and I'm blocked as I can only initiate the gallery if i manually reload the page.

**Comment by OriginalEXE** [comment]
@Julien76 you can still manually destroy the flexImages if you need to, the script does it itself internally, it would just be nice to have a nicer method than to manually remove data() from the element.

**Comment by berndschimmer** [comment]
If you really need it, you could use my fork or fork it again:
https://github.com/berndschimmer/jQuery-flexImages

**Comment by Julien76** [comment]
@berndschimmer, I looked at your fork but I'm not sure to understand how to call the destroy function.
 @OriginalEXE, how do you remove data() from the element?
Sorry for these questions, but i'm rather a beginner in javascript :)

**Comment by OriginalEXE** [comment]
@Julien76 You simply call this:
`jQuery( window ).off( 'resize.flexImages' + jQuery( 'YourGridSelectorHere').data( 'flex-t' ) );`

This will remove the single event that is bound to the grid, then you can just remove the grid element itself and you have effectively cleaned up the grid.
