### ISSUE TITLE
Min-width for item

### ISSUE THREAD

**Issue by bogdosarov** [Pixabay/jQuery-flexImages#4]
Hi. Thank you very much for this excellent plugin! Can you help my with min-width size of item.  I added minWidth option.
```javascript
var o = $.extend({
            container: '.item',
            object: 'img',
            rowHeight: 180,
            maxRows: 0,
            truncate: false,
            minWidth: 180
        }, options);
```

Then in function 'makeGrid' i do check 
```javascript
var tempWidth = Math.ceil(row[x][3]*ratio);
new_w = o.minWidth > tempWidth ? o.minWidth : tempWidth;
```
It works, but it doesn't work in '_helper' function. 
When i insert code for verify in '_helper' function then i have broken grid.

**Comment by SimonSteinberger** [comment]
This will probably cause other issues with the grid. When limiting the width, the image will get too high for this row. Maybe you can work with "overflow: hidden" to compensate for this. In any case it *might* be more complicated than one would expect.

new_w is a "global" variable inside the plugin - so inside the _helper it's the same as outside. So, I guess the grid may be broken because the image simply gets too high. If you like, you can provide a screenshot or a JSFiddle ...
