### ISSUE TITLE
Fleximages on firefox android having issues

### ISSUE THREAD

**Issue by Jean-Luc-Hauser** [Pixabay/jQuery-flexImages#9]
Hi, 

It seems the android Firefox browser (37.0.1) does not display correctly the grid, the last image on a row is always shifted down, I would love to find a workaround, does anybody has any clues, would be awesome :)

Thanks for this great plugin.

**Comment by SimonSteinberger** [comment]
Hmm, I just freshly installed FF 37.0.1 on my Samsung/Android and it appeared to be working correctly. Does the demo page show this issue on your device?

It's hard to debug without actually observing the issue ... so I appreciate any hint.

**Comment by Jean-Luc-Hauser** [comment]
Hi Simon,

Sorry I should have mentioned that it was on the demo page (http://goodies.pixabay.com/jquery/flex-images/demo.html) , on a Nexus 7 (2012), FF37.0.1 here is a picture of the screen in portrait mode.

![fleximages](https://cloud.githubusercontent.com/assets/11922698/7117122/0dc68fe6-e1f7-11e4-90a5-3506b0532f40.png)

The same page in landscape only has the last picture of row 1 out of place.

![fleximage-landscape](https://cloud.githubusercontent.com/assets/11922698/7117268/e732c970-e1f7-11e4-97f7-8c339ea365b6.png)

**Comment by SimonSteinberger** [comment]
OK, these screenshots help a lot.

Actually, it's not the last line that is wrong. The container's width is apparently returned incorrect. As a result, the image rows are basically overflowing, because the plugin "thinks" there's more space available.

If you look closely and compare the gallery with a normal browser, you'll notice it's actually the first row that shows also the first error. The last image that should fit into this row breaks into the next one - and consequently, the whole layout gets chaotic.

It's a typical "1 pixel too large or too small" problem ... maybe this FF version doesn't take borders into account when returning the container's width or something alike.

Wish I could debug this on my own, but I just can't observe it. Neither on my own Android device, nor in Chrome's simulated Nexus 7 emulator.

Well, I've just found a minor bug that *might* have been responsible. Just make sure to clear your cache before testing :-)

**Comment by Jean-Luc-Hauser** [comment]
I did some more testing, on the same page (http://lemurdesphotographes.com), chrome returned a .width() of 540, and FF = 541 !

So I did modified the "makeGrid(grid, items, o, noresize)" function, I tried with "max_w = grid.width()-1" but same results, I had to substract 2px ( max_w = grid.width()-2 ) to have it work.

Beats me why 2px and not 1px ... It sucks monkeys balls because you can see a blank of 2px on the right

I have a test page on http://foo.lemurdesphotographes.com where after the grid, there is a form with the value of the width of the div (at the end of the page).

**Comment by SimonSteinberger** [comment]
That's a weird FF result for the width :-P
You could play around with borders, margins, paddings, and border-box. Maybe there's a workaround, and maybe that could also show the cause ... Really hard to say; my local FF returns the same width, at least on the demo page.

If you like, you could try the plain JS version of flexImages. It doesn't make use of jQuery $.width(), but the vanilla JS version has no support for IE7. It's bundled in the GitHub package. Just include the other script and initialize your grids with something like that:

new flexImages({selector: '#demo1', rowHeight: 140});

**Comment by SimonSteinberger** [comment]
On my Samsung Android 4.x, FF and Chrome also show the same width, 324 px. So it seems to be a pretty specific problem of the Nexus or this particular Android version or something.

**Comment by Portugao** [comment]
Sorry, I get the same issue with android 4.2.2 and firefox 39.0 on mobistel phone.

**Comment by velizarov** [comment]
Hi All,

I had the same issue and fix it today. Reducing of the item width by 2 px was enough for me. I will test using Chrome in Desctop and mobile IE.

See my commit in pull request.

I glad to have the plugin. I am going to proceed further to be able to show large image.

Better to implement into this component, but it is other story.

Best regards,
Vladimir

**Comment by SimonSteinberger** [comment]
Thanks Jean-Luc-Hauser,I've included your version. Even if I have never seen this issue for myself, I guess your solution does the trick.
